apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
    tier: backend
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    ports:
    - containerPort: 3306
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    livenessProbe:
      exec:
        command:
        - mysqladmin
        - ping
        - -proot
      initialDelaySeconds: 20
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - mysqladmin
        - ping
        - -proot
      initialDelaySeconds: 10
      periodSeconds: 5